import type { PiggyTrackData } from "@/domain/entities";

export const mockData: PiggyTrackData = {
  investments: [],
  batches: [
    {
      id: "batch-tabeki-2026",
      name: "Piggy Bank — Tabeki 2026",
      startDate: "2026-03-28",
      endDate: null,
      status: "Active",
      notes: "First Tabeki cycle for 2026.",
      createdAt: "2026-03-28T08:00:00+08:00",
      updatedAt: "2026-07-30T18:00:00+08:00",
    },
    {
      id: "batch-harvest-2025",
      name: "Harvest Batch — 2025",
      startDate: "2025-04-12",
      endDate: "2025-09-06",
      status: "Completed",
      notes: "Previous completed cycle.",
      createdAt: "2025-04-12T08:00:00+08:00",
      updatedAt: "2025-09-06T16:00:00+08:00",
    },
  ],
  pigs: Array.from({ length: 6 }, (_, index) => ({
    id: `pig-${index + 1}`,
    batchId: "batch-tabeki-2026",
    tagNumber: `TBK-${String(index + 1).padStart(2, "0")}`,
    purchasePrice: 4200,
    purchaseWeight: 22 + index,
    currentWeight: [73, 76, 63, 80, 83, 74][index],
    status: "Sold" as const,
    notes: "",
  })),
  expenses: [
    {
      id: "ex-1",
      batchId: "batch-tabeki-2026",
      category: "Piglets",
      description: "Six piglets",
      quantity: 6,
      unit: "head",
      unitPrice: 4200,
      expenseDate: "2026-03-28",
      notes: "Purchased from Doris",
    },
    {
      id: "ex-2",
      batchId: "batch-tabeki-2026",
      category: "Vitamins",
      description: "Vitamins and dewormer",
      quantity: 1,
      unit: "set",
      unitPrice: 1000,
      expenseDate: "2026-03-28",
      notes: "",
    },
    {
      id: "ex-3",
      batchId: "batch-tabeki-2026",
      category: "Vitamins",
      description: "Vitamin Pro",
      quantity: 1,
      unit: "pack",
      unitPrice: 600,
      expenseDate: "2026-04-02",
      notes: "",
    },
    {
      id: "ex-4",
      batchId: "batch-tabeki-2026",
      category: "Medicine",
      description: "Apralyte",
      quantity: 1,
      unit: "pack",
      unitPrice: 500,
      expenseDate: "2026-04-02",
      notes: "",
    },
    {
      id: "ex-5",
      batchId: "batch-tabeki-2026",
      category: "Feed",
      feedType: "Pre Starter",
      description: "Pre Starter feed",
      quantity: 2,
      unit: "sack",
      unitPrice: 1323,
      expenseDate: "2026-03-27",
      notes: "",
    },
    {
      id: "ex-6",
      batchId: "batch-tabeki-2026",
      category: "Feed",
      feedType: "Starter Premium",
      description: "Starter Premium feed",
      quantity: 5,
      unit: "sack",
      unitPrice: 1915,
      expenseDate: "2026-04-24",
      notes: "Combined purchases",
    },
    {
      id: "ex-7",
      batchId: "batch-tabeki-2026",
      category: "Feed",
      feedType: "Grower",
      description: "Grower feed",
      quantity: 12,
      unit: "sack",
      unitPrice: 1807.5,
      expenseDate: "2026-06-14",
      notes: "Combined purchases",
    },
    {
      id: "ex-8",
      batchId: "batch-tabeki-2026",
      category: "Feed",
      feedType: "Finisher",
      description: "Finisher feed",
      quantity: 6.4,
      unit: "sack",
      unitPrice: 1844.21875,
      expenseDate: "2026-07-27",
      notes: "Includes partial sacks",
    },
    {
      id: "ex-9",
      batchId: "batch-tabeki-2026",
      category: "Pig House Repair",
      description: "Drinker materials",
      quantity: 1,
      unit: "set",
      unitPrice: 800,
      expenseDate: "2026-03-25",
      notes: "",
    },
    {
      id: "ex-10",
      batchId: "batch-tabeki-2026",
      category: "Pig House Repair",
      description: "Pig house repair",
      quantity: 1,
      unit: "project",
      unitPrice: 7264,
      expenseDate: "2026-03-26",
      notes: "Materials, snacks, and labor",
    },
  ],
  buyers: [
    {
      id: "buyer-1",
      name: "Noy Boboy Slaughter House",
      contactInformation: "Tabeki, Benguet",
      notes: "Primary buyer",
    },
    { id: "buyer-2", name: "Jocelyn", contactInformation: "", notes: "Individual buyer" },
  ],
  sales: [
    {
      id: "sale-1",
      pigId: "pig-1",
      batchId: "batch-tabeki-2026",
      buyerId: "buyer-1",
      actualWeight: 73,
      weightDeduction: 1,
      pricePerKg: 190,
      saleDate: "2026-07-23",
      paymentDueDate: "2026-07-31",
      notes: "",
    },
    {
      id: "sale-2",
      pigId: "pig-2",
      batchId: "batch-tabeki-2026",
      buyerId: "buyer-1",
      actualWeight: 76,
      weightDeduction: 1,
      pricePerKg: 190,
      saleDate: "2026-07-28",
      paymentDueDate: "2026-08-04",
      notes: "",
    },
    {
      id: "sale-3",
      pigId: "pig-3",
      batchId: "batch-tabeki-2026",
      buyerId: "buyer-1",
      actualWeight: 63,
      weightDeduction: 1,
      pricePerKg: 190,
      saleDate: "2026-07-29",
      paymentDueDate: "2026-08-04",
      notes: "",
    },
    {
      id: "sale-4",
      pigId: "pig-4",
      batchId: "batch-tabeki-2026",
      buyerId: "buyer-1",
      actualWeight: 80,
      weightDeduction: 1,
      pricePerKg: 190,
      saleDate: "2026-07-29",
      paymentDueDate: "2026-08-05",
      notes: "",
    },
    {
      id: "sale-5",
      pigId: "pig-5",
      batchId: "batch-tabeki-2026",
      buyerId: "buyer-1",
      actualWeight: 83,
      weightDeduction: 1,
      pricePerKg: 185,
      saleDate: "2026-07-29",
      paymentDueDate: "2026-08-05",
      notes: "",
    },
    {
      id: "sale-6",
      pigId: "pig-6",
      batchId: "batch-tabeki-2026",
      buyerId: "buyer-1",
      actualWeight: 74,
      weightDeduction: 1,
      pricePerKg: 190,
      saleDate: "2026-07-30",
      paymentDueDate: "2026-08-06",
      notes: "",
    },
  ],
  payments: [
    {
      id: "pay-1",
      saleId: "sale-1",
      amount: 8000,
      paymentDate: "2026-07-31",
      paymentMethod: "Cash",
      notes: "First partial payment",
    },
    {
      id: "pay-2",
      saleId: "sale-1",
      amount: 3880,
      paymentDate: "2026-08-02",
      paymentMethod: "GCash",
      notes: "Remaining ₱1,800 pending",
    },
    {
      id: "pay-3",
      saleId: "sale-2",
      amount: 14250,
      paymentDate: "2026-08-04",
      paymentMethod: "Cash",
      notes: "",
    },
    {
      id: "pay-4",
      saleId: "sale-3",
      amount: 11780,
      paymentDate: "2026-08-04",
      paymentMethod: "Cash",
      notes: "",
    },
    {
      id: "pay-5",
      saleId: "sale-4",
      amount: 15010,
      paymentDate: "2026-08-05",
      paymentMethod: "Bank Transfer",
      notes: "",
    },
    {
      id: "pay-6",
      saleId: "sale-5",
      amount: 15170,
      paymentDate: "2026-08-05",
      paymentMethod: "Bank Transfer",
      notes: "",
    },
    {
      id: "pay-7",
      saleId: "sale-6",
      amount: 13870,
      paymentDate: "2026-08-06",
      paymentMethod: "GCash",
      notes: "",
    },
  ],
};
